<?php
/**
 * Returns a list of theme modification settings and their defaults. Used by
 * `style.php` and the theme customizer.
 * 
 * @return array
 */

return array(
	'content' => 'one-column',
	'sidebar1_width' => 25,
	'sidebar2_width' => 25,
	'min_width' => 0,
	'max_width' => 0,
	'responsive_width' => 0,
	'font_size' => 100,
	'font' => '',
	'header_font' => '',
	'page_font' => '',
	'title_font' => '',
	'trim_font' => '',
	'background_color' => '#fff',
	'background_opacity' => 1,
	'page_color' => '#fff',
	'page_opacity' => 1,
	'trim_color' => '#222',
	'trim_opacity' => 1,
	'text_color' => '#222',
	'text_opacity' => 1,
	'header_textcolor' => 'blank',
	'header_textopacity' => 1,
	'page_text_color' => '#222',
	'page_text_opacity' => 1,
	'trim_text_color' => '#fff',
	'trim_text_opacity' => 1,
	'link_color' => '#999',
	'link_opacity' => 1,
	'link_hover_color' => '#222',
	'link_hover_opacity' => 1,
	'page_link_color' => '#999',
	'page_link_opacity' => 1,
	'page_link_hover_color' => '#222',
	'page_link_hover_opacity' => 1,
	'trim_link_color' => '#999',
	'trim_link_opacity' => 1,
	'trim_link_hover_color' => '#fff',
	'trim_link_hover_opacity' => 1,
	'background_image' => '',
	'background_repeat' => '',
	'background_position_x' => '',
	'background_attachment' => '',
	'page_background_image' => '',
	'page_background_repeat' => '',
	'page_background_position_x' => '',
	'page_background_attachment' => '',
	'trim_background_image' => '',
	'trim_background_repeat' => '',
	'trim_background_position_x' => '',
	'trim_background_attachment' => ''
);